steps:
  # Step 1: Install dependencies
  - name: node
    entrypoint: npm
    args: ['install']

  # Step 2: Build the app
  - name: node
    entrypoint: npm
    args: ['run', 'build']

  # Step 3: Deploy the app to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app deploy
      - --quiet
      - app.yaml
      - --promote
      - --stop-previous-version

timeout: 1800s
